[project]
name = "fileman"
version = "1.0.0"
description = "Fileman CLI"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
]

[project.scripts]
fileman = "fileman.main:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
